### PR TITLE
Fix issue not copying URL to clipboard

### PR DESCRIPTION
**Pull request by jtapia**

### CODE REVIEW

**Comment by fastjames** [comment]
@jtapia I made a new PR to address the sqlite3 version mismatch, please take a look.

**Comment by jtapia** [comment]
https://app.clubhouse.io/enginecommerce/story/3677/user-cannot-copy-premade-cart-url-using-copy-link-button

**Comment by fastjames** [comment]
Rebased to incorporate spec fixes, force-pushed.

**Review by fastjames — APPROVED** [review]
I verified that this worked as expected locally.

**Pull request merged**
